language: java
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
env:
  - STUCCO_DB_TYPE=INMEMORY
  - STUCCO_DB_CONFIG="config/inmemory.yml"
  - STUCCO_DB_INDEX_CONFIG="config/inmemory.yml"
after_success:
  - wget https://raw.githubusercontent.com/stucco/test/master/rerun-test.sh
  - chmod a+x ./rerun-test.sh
  - ./rerun-test.sh
notifications:
  slack: sava:lB0VBcWKom3VNlr126hyI04E