language: java
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
addons:
  - postgresql: "9.3"
before_script:
  - psql -c "CREATE USER stucco WITH PASSWORD 'stucco' CREATEDB CREATEROLE SUPERUSER REPLICATION;" -U postgres
  - psql -c 'create database testdb;' -U stucco
env:
  - STUCCO_DB_TYPE=POSTGRESQL STUCCO_DB_CONFIG="config/postgresql.yml" STUCCO_DB_INDEX_CONFIG=""
after_success:
  - wget https://raw.githubusercontent.com/stucco/test/master/rerun-test.sh
  - chmod a+x ./rerun-test.sh
  - ./rerun-test.sh
notifications:
  slack: sava:lB0VBcWKom3VNlr126hyI04E
